from gui.pages.about_page import AboutPage
from gui.pages.class_page import ClassPage
from gui.pages.def_page import DefPage
from gui.pages.dict_page import DictPage
from gui.pages.for_page import ForPage
from gui.pages.general_page import GeneralPage
from gui.pages.list_page import ListPage
from gui.pages.listcomp_page import ListCompPage
from gui.pages.print_page import PrintPage
from gui.pages.set_page import SetPage
from gui.pages.str_page import StrPage
from gui.pages.tuple_page import TuplePage
